### ISSUE TITLE
Show username on message

### ISSUE THREAD

**Issue by viniciuspietscher** [badgerbadgers/ctd-sparrow-chat-app#128]
![image](https://user-images.githubusercontent.com/8095975/186767030-b779c0d3-932f-4810-8f00-c1ae798f9778.png)

**Comment by asaiapalacios** [comment]
I will go ahead and continue focusing on my current task - the sidebar. Will open this up to anyone (it looks like it'll be fun to implement)

**Comment by badgerbadgers** [comment]
@viniciuspietscher looks great Vini!
@asaiapalacios thanks Asaia. I want to eventually make mobile. Will look at how bootstrap deals with a sidebar and sidebar functionality.
