### ISSUE TITLE
UI: set max-width for chat bubbles

### ISSUE THREAD

**Issue by viniciuspietscher** [badgerbadgers/ctd-sparrow-chat-app#137]
I think it would look cool if the chat bubbles were a different size for each message, we can easily change it by doing the following, what you all think?

![image](https://user-images.githubusercontent.com/8095975/186986336-d0b72eb4-3f86-4377-907b-c48acf25f08a.png)

**Comment by asaiapalacios** [comment]
Yes, I agree. The chat bubbles with different sizes looks good.
