### ISSUE TITLE
User can register with email and password (firebase)

### ISSUE THREAD

**Issue by LawrenceELee** [badgerbadgers/ctd-sparrow-chat-app#168]
Whoever is assigned to this task could use the RightSideComponent to display User information. Whoever works on task could also create a new Sign Up page, where the user will sign up with their email and create a secure password.

**Comment by badgerbadgers** [comment]
closed with PR: [https://github.com/badgerbadgers/ctd-sparrow-chat-app/pull/181](https://github.com/badgerbadgers/ctd-sparrow-chat-app/pull/181)
