### ISSUE TITLE
Update README (last week)

### ISSUE THREAD

**Issue by viniciuspietscher** [badgerbadgers/ctd-sparrow-chat-app#72]
- Project description, goals;
- Screenshots/short video of app working;
- Information on how to access deployed app;
- Information about how to run the project locally (requirements like node, npm, firebase...) and commands to run locally;
- Thank you section for Justin and the CTD team;

Edit: I'll assign everyone to this one, because documentation should also be part of our job.
Each of us can work on a different section to avoid difficult to resolve merge conflicts.

Since Readme is written in markdown, here is a cheatsheet for it:
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Here is some examples:

- https://github.com/facebook/react#readme
- https://github.com/microsoft/TypeScript/#readme
- https://github.com/cypress-io/cypress#readme

**Comment by LawrenceELee** [comment]
Lawrence: Screenshots and video.
Asaia: Firebase walkthrough - how to create and initialize it, create tokens.
