### ISSUE TITLE
Bug: Add default image in navbar when...

### ISSUE THREAD

**Issue by asaiapalacios** [badgerbadgers/ctd-sparrow-chat-app#83]
- user does not have a profile pic; or
- user account pic is not rendering (user gets a loading-pic icon instead)

**Comment by viniciuspietscher** [comment]
We also need to add a default image for the messages as well!



![Image](https://user-images.githubusercontent.com/8095975/185640349-6e1ba984-4830-4efe-b479-dcea6f1fe4fa.png)

**Comment by badgerbadgers** [comment]
For sure this is version 1 of the navbar I don't really like the large text myself and will move the content a little will work on this today.

**Comment by badgerbadgers** [comment]
Just pushed version 2, version 3 will include this next @asaiapalacios @viniciuspietscher
