### ISSUE TITLE
Hide "Sign Out" button from navbar if there is no user signed in

### ISSUE THREAD

**Issue by viniciuspietscher** [badgerbadgers/ctd-sparrow-chat-app#88]
Right now we are displaying the "Sign out" button even if there is no user signed in.

I see two options:

1. Hide the button if there is not a user signed in;
2. Change the button to a Sign in if user is signed out.

![Image](https://user-images.githubusercontent.com/8095975/185639706-672c61f8-67e4-4046-a1b6-5472c8884daa.png)

**Comment by badgerbadgers** [comment]
I thought it looks cleaner if the navbar would only display if user was logged in and have it included in the path '/chat' again. Should be simple enough to hide the button if user is signed out of google account. Feel free to create a branch @viniciuspietscher , UI is important! We can compare different versions.
