### ISSUE TITLE
Feature: Show messages timestamp

### ISSUE THREAD

**Issue by viniciuspietscher** [badgerbadgers/ctd-sparrow-chat-app#89]
This can be a stretch goal, but I think it would be cool to include another external npm package on our app.

We can use the package https://www.npmjs.com/package/javascript-time-ago to include a timestamp on the message

![Image](https://user-images.githubusercontent.com/8095975/185647557-42136406-bc5b-4993-9e80-e6ac3127bc97.png)

we have previously used this library while building the twitter app with Karson
https://github.com/karsonkalt/CTD_React_App/blob/master/src/components/Tweet/index.jsx

**Comment by badgerbadgers** [comment]
I figure we can work this in next week if anything.

**Comment by badgerbadgers** [comment]
Refer to timeago.js package that was downloaded for this feature. [](https://www.npmjs.com/package/javascript-time-ago)

**Comment by viniciuspietscher** [comment]
pushed a PR with timestamp implemented, need someone to finish migrating the styling to the new component.
